import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";
import * as cp from "child_process";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Registry {
  GP: number;
  GC: number;
  EV: number;
  FR: number;
  lastUpdated: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getAigapDir(workspaceRoot: string): string {
  return path.join(workspaceRoot, ".aigap");
}

function getRegistry(aigapDir: string): Registry {
  const registryPath = path.join(aigapDir, "registry.json");
  if (!fs.existsSync(registryPath)) {
    return { GP: 0, GC: 0, EV: 0, FR: 0, lastUpdated: new Date().toISOString().split("T")[0] };
  }
  return JSON.parse(fs.readFileSync(registryPath, "utf-8")) as Registry;
}

function saveRegistry(aigapDir: string, registry: Registry): void {
  registry.lastUpdated = new Date().toISOString().split("T")[0];
  fs.writeFileSync(path.join(aigapDir, "registry.json"), JSON.stringify(registry, null, 2));
}

function nextId(type: keyof Omit<Registry, "lastUpdated">, registry: Registry): string {
  registry[type] += 1;
  return `${type}-${String(registry[type]).padStart(3, "0")}`;
}

function getWorkspaceRoot(): string | undefined {
  return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
}

function requireWorkspace(): string {
  const root = getWorkspaceRoot();
  if (!root) {
    vscode.window.showErrorMessage("aigap: No workspace folder open.");
    throw new Error("No workspace");
  }
  return root;
}

function ensureAigapDir(root: string): string {
  const dir = getAigapDir(root);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

function openDocument(filePath: string): void {
  vscode.workspace.openTextDocument(filePath).then((doc) => {
    vscode.window.showTextDocument(doc);
  });
}

function showInfo(msg: string): void {
  vscode.window.showInformationMessage(`aigap: ${msg}`);
}

function showError(msg: string): void {
  vscode.window.showErrorMessage(`aigap: ${msg}`);
}

async function pickFile(label: string): Promise<vscode.Uri | undefined> {
  const uris = await vscode.window.showOpenDialog({
    canSelectMany: false,
    openLabel: label,
    filters: { "Policy Documents": ["md", "txt", "pdf", "docx"] },
  });
  return uris?.[0];
}

// ---------------------------------------------------------------------------
// Command implementations
// ---------------------------------------------------------------------------

async function cmdInit(): Promise<void> {
  const root = requireWorkspace();
  const fileUri = await pickFile("Select policy document");
  if (!fileUri) return;

  const aigapDir = ensureAigapDir(root);
  const registry = getRegistry(aigapDir);

  const policiesPath = path.join(aigapDir, "POLICIES.md");
  const date = new Date().toISOString().split("T")[0];

  // Stub — in production this calls Copilot LLM on the file contents
  const stub = `# POLICIES — ${path.basename(root)}
<!-- aigap v0.1.0 · generated by aigap.init · ${date} -->

version: 0.1.0
updated: ${date}
author: Anirudh Yadav

---

## Summary

| Type | Count |
|---|---|
| Guardrail Categories (GC) | 0 |
| Guardrail Policies (GP) | 0 |
| Enforcement Vectors (EV) | 0 |

---

> Edit this file or re-run **aigap: Initialize from Policy Doc** with your full policy document.
> Source: ${fileUri.fsPath}
`;

  fs.writeFileSync(policiesPath, stub);
  saveRegistry(aigapDir, registry);
  openDocument(policiesPath);
  showInfo(`Initialized .aigap/POLICIES.md from ${path.basename(fileUri.fsPath)}`);
}

async function cmdUpdate(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const policiesPath = path.join(aigapDir, "POLICIES.md");

  if (!fs.existsSync(policiesPath)) {
    showError("POLICIES.md not found. Run aigap: Initialize first.");
    return;
  }

  const name = await vscode.window.showInputBox({ prompt: "Guardrail policy name (e.g. No PII in prompt)" });
  if (!name) return;

  const description = await vscode.window.showInputBox({ prompt: "Description (1–2 sentences, precise and enforceable)" });
  if (!description) return;

  const severity = await vscode.window.showQuickPick(["critical", "high", "medium", "low"], { placeHolder: "Severity" });
  if (!severity) return;

  const registry = getRegistry(aigapDir);
  const gpId = nextId("GP", registry);
  const date = new Date().toISOString().split("T")[0];

  const entry = `\n| ${gpId} | ${name} | ${description} | ${severity} | — | 🔲 gap |\n`;
  fs.appendFileSync(policiesPath, entry);
  saveRegistry(aigapDir, registry);

  showInfo(`${gpId} added to POLICIES.md`);
  vscode.commands.executeCommand("aigap.validate");
}

async function cmdValidate(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = getAigapDir(root);
  const policiesPath = path.join(aigapDir, "POLICIES.md");

  if (!fs.existsSync(policiesPath)) {
    showError("POLICIES.md not found. Run aigap: Initialize first.");
    return;
  }

  const content = fs.readFileSync(policiesPath, "utf-8");
  const idPattern = /GP-(\d{3})/g;
  const ids: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = idPattern.exec(content)) !== null) {
    ids.push(match[0]);
  }

  const duplicates = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (duplicates.length > 0) {
    showError(`Duplicate IDs found: ${[...new Set(duplicates)].join(", ")}`);
    return;
  }

  // Write traceability index stub
  const indexPath = path.join(aigapDir, "index.md");
  const date = new Date().toISOString().split("T")[0];
  const indexContent = `# Policy Traceability Index
<!-- updated: ${date} -->

| ID | Name | File | Test | Status |
|---|---|---|---|---|
${ids.map((id) => `| ${id} | — | — | — | 🔲 gap |`).join("\n")}
`;
  fs.writeFileSync(indexPath, indexContent);
  showInfo(`POLICIES.md valid — ${ids.length} policies, index.md updated`);
}

async function cmdGapReport(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const editor = vscode.window.activeTextEditor;

  const target = editor ? editor.document.fileName : root;
  const label = editor ? path.basename(target) : "workspace";

  // Scan for GP-NNN references in the target file / workspace
  const grepResult = cp.spawnSync("grep", ["-rn", "GP-[0-9]\\{3\\}", target], { encoding: "utf-8" });
  const references = grepResult.stdout || "(no GP-NNN references found)";

  const gapPath = path.join(aigapDir, "gap-report.md");
  const date = new Date().toISOString().split("T")[0];

  const content = `# Gap Report — ${label}
<!-- aigap · ${date} -->

## GP-NNN references found

\`\`\`
${references}
\`\`\`

## Cross-reference with POLICIES.md

Run \`aigap check . --policy .aigap-policy.yaml\` for full enforcement gap analysis.
`;
  fs.writeFileSync(gapPath, content);
  openDocument(gapPath);
  showInfo("Gap report written to .aigap/gap-report.md");
}

async function cmdEnforcement(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const enforcementDir = path.join(aigapDir, "enforcement");
  if (!fs.existsSync(enforcementDir)) fs.mkdirSync(enforcementDir, { recursive: true });

  const language = await vscode.window.showQuickPick(["Python", "TypeScript", "Java"], {
    placeHolder: "Target language for enforcement stubs",
  });
  if (!language) return;

  const ext = language === "Python" ? "py" : language === "TypeScript" ? "ts" : "java";
  const stubPath = path.join(enforcementDir, `enforcement_stubs.${ext}`);

  const stubContent =
    language === "Python"
      ? `# aigap enforcement stubs — generated ${new Date().toISOString().split("T")[0]}
# Add GP-NNN IDs to implement specific policies

def pre_call_hook(prompt: str) -> str:
    """EV-001: pre-call hook — runs before every LLM call."""
    # GP-001: No PII in prompt
    _check_no_pii(prompt)
    return prompt

def output_filter(response: str) -> str:
    """EV-002: output filter — runs after every LLM response."""
    return response

def _check_no_pii(text: str) -> None:
    """GP-001 enforcement: raise if PII detected."""
    import re
    patterns = [r"\\b\\d{3}-\\d{2}-\\d{4}\\b", r"\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"]
    for pattern in patterns:
        if re.search(pattern, text):
            raise ValueError(f"GP-001 violation: PII detected in text")
`
      : `// aigap enforcement stubs — generated ${new Date().toISOString().split("T")[0]}
// Add GP-NNN IDs to implement specific policies

export function preCallHook(prompt: string): string {
  // EV-001: pre-call hook
  checkNoPii(prompt); // GP-001
  return prompt;
}

export function outputFilter(response: string): string {
  // EV-002: output filter
  return response;
}

function checkNoPii(text: string): void {
  const ssnPattern = /\\b\\d{3}-\\d{2}-\\d{4}\\b/;
  if (ssnPattern.test(text)) {
    throw new Error("GP-001 violation: PII detected in text");
  }
}
`;

  fs.writeFileSync(stubPath, stubContent);
  openDocument(stubPath);
  showInfo(`Enforcement stubs written to .aigap/enforcement/enforcement_stubs.${ext}`);
}

async function cmdAuditReport(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);

  const fileUri = await pickFile("Select audit log file (JSON or JSONL)");
  if (!fileUri) return;

  const auditPath = path.join(aigapDir, "audit-report.md");
  const date = new Date().toISOString().split("T")[0];

  const content = `# Audit Report
<!-- aigap · ${date} · source: ${path.basename(fileUri.fsPath)} -->

| Timestamp | GP-NNN | Verdict | Evidence |
|---|---|---|---|
| ${date} | GP-001 | pass | — |

> Full mapping requires running \`aigap check\` with \`--output aigap-report.json\`.
`;
  fs.writeFileSync(auditPath, content);
  openDocument(auditPath);
  showInfo("Audit report written to .aigap/audit-report.md");
}

async function cmdChangeImpact(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);

  const oldUri = await pickFile("Select OLD policy document");
  if (!oldUri) return;
  const newUri = await pickFile("Select NEW policy document");
  if (!newUri) return;

  const reportPath = path.join(aigapDir, "change-impact-report.md");
  const date = new Date().toISOString().split("T")[0];

  const content = `# Change Impact Report
<!-- aigap · ${date} -->

Old: ${path.basename(oldUri.fsPath)}
New: ${path.basename(newUri.fsPath)}

## Added policies
_(run with LLM to extract)_

## Removed / deprecated policies
_(run with LLM to extract)_

## Changed severity
_(run with LLM to extract)_

## Breaking changes
_(policies removed that have active enforcement stubs)_
`;
  fs.writeFileSync(reportPath, content);
  openDocument(reportPath);
  showInfo("Change impact report written to .aigap/change-impact-report.md");
}

async function cmdFrameworkMap(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const registry = getRegistry(aigapDir);

  const frameworks = await vscode.window.showQuickPick(
    ["EU AI Act", "NIST AI RMF", "ISO 42001", "GDPR Art.22"],
    { placeHolder: "Select frameworks to map", canPickMany: true }
  );
  if (!frameworks || frameworks.length === 0) return;

  const frId = nextId("FR", registry);
  saveRegistry(aigapDir, registry);

  const mapPath = path.join(aigapDir, "framework-map.md");
  const date = new Date().toISOString().split("T")[0];

  const content = `# Framework Map
<!-- aigap · ${date} · frameworks: ${frameworks.join(", ")} -->

| GP-NNN | Policy Name | ${frameworks.join(" | ")} |
|---|---|${frameworks.map(() => "---|").join("")}
| GP-001 | — | ${frameworks.map(() => "— |").join("")}

> First FR-NNN assigned: ${frId}. Run with LLM for full clause mapping.
`;
  fs.writeFileSync(mapPath, content);
  openDocument(mapPath);
  showInfo(`Framework map written to .aigap/framework-map.md (${frId} assigned)`);
}

async function cmdSprintFeed(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const gapPath = path.join(aigapDir, "gap-report.md");

  if (!fs.existsSync(gapPath)) {
    showError("gap-report.md not found. Run aigap: Show Gap Report first.");
    return;
  }

  const sprintPath = path.join(aigapDir, "sprint-feed.md");
  const date = new Date().toISOString().split("T")[0];

  const content = `# Sprint Feed
<!-- aigap · ${date} -->

| TASK-NNN | GP-NNN | Title | Story Points | Assignee |
|---|---|---|---|---|
| TASK-001 | GP-001 | Implement pre-call PII hook | 3 | — |
| TASK-002 | GP-002 | Add output filter for PII | 2 | — |

> Generated from .aigap/gap-report.md. Copy TASK-NNN cards into your sprint board.
`;
  fs.writeFileSync(sprintPath, content);
  openDocument(sprintPath);
  showInfo("Sprint feed written to .aigap/sprint-feed.md");
}

async function cmdPrDraft(): Promise<void> {
  const root = requireWorkspace();

  const gitDiff = cp.spawnSync("git", ["diff", "--name-only", "HEAD"], {
    cwd: root,
    encoding: "utf-8",
  });
  const changedFiles = gitDiff.stdout?.trim() || "(no git diff available)";

  const content = `## Summary

<!-- Describe what changed -->

## Policies affected

| GP-NNN | Policy Name | Status |
|---|---|---|
| — | — | enforced / gap |

## Changed files

${changedFiles
  .split("\n")
  .filter(Boolean)
  .map((f) => `- \`${f}\``)
  .join("\n")}

## Enforcement evidence

- [ ] Enforcement stub committed
- [ ] Test referencing GP-NNN committed
- [ ] \`aigap check\` passes locally

🤖 Generated by aigap · github.com/anirudhyadav/aigap
`;

  const doc = await vscode.workspace.openTextDocument({
    language: "markdown",
    content,
  });
  await vscode.window.showTextDocument(doc);
  showInfo("PR draft opened — copy into your PR description");
}

async function cmdReleaseNotes(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const releasesDir = path.join(aigapDir, "releases");
  if (!fs.existsSync(releasesDir)) fs.mkdirSync(releasesDir, { recursive: true });

  const version = await vscode.window.showInputBox({ prompt: "Release version tag (e.g. v1.2.0)" });
  if (!version) return;

  const gitLog = cp.spawnSync("git", ["log", "--oneline", "-20"], { cwd: root, encoding: "utf-8" });
  const commits = gitLog.stdout?.trim() || "(no git log available)";

  const notesPath = path.join(releasesDir, `${version}.md`);
  const date = new Date().toISOString().split("T")[0];

  const content = `# Release Notes — ${version}
<!-- aigap · ${date} -->

## Policies enforced this release

| GP-NNN | Policy Name | Enforcement Added |
|---|---|---|
| — | — | — |

## Recent commits

\`\`\`
${commits}
\`\`\`
`;
  fs.writeFileSync(notesPath, content);
  openDocument(notesPath);
  showInfo(`Release notes written to .aigap/releases/${version}.md`);
}

async function cmdStatusReport(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);
  const releasesDir = path.join(aigapDir, "releases");
  if (!fs.existsSync(releasesDir)) fs.mkdirSync(releasesDir, { recursive: true });

  const version = await vscode.window.showInputBox({ prompt: "Report version label (e.g. v1.2.0)" });
  if (!version) return;

  const policiesPath = path.join(aigapDir, "POLICIES.md");
  const hasPolicies = fs.existsSync(policiesPath);
  const policyCount = hasPolicies
    ? (fs.readFileSync(policiesPath, "utf-8").match(/GP-\d{3}/g) || []).length
    : 0;

  const statusPath = path.join(releasesDir, `status-${version}.md`);
  const date = new Date().toISOString().split("T")[0];

  const content = `# Policy Status Report — ${version}
<!-- aigap · ${date} -->

## At a glance

| Metric | Value |
|---|---|
| Policies defined | ${policyCount} |
| Policies enforced | — |
| Policies with tests | — |
| Framework mapped | — |
| Overall compliance | —% |

## What's in scope

_(Describe the AI system and release scope)_

## What's enforced

_(List GP-NNN IDs that are fully enforced)_

## What's still a gap

_(List GP-NNN IDs that are 🔲 gap — and the plan)_
`;
  fs.writeFileSync(statusPath, content);
  openDocument(statusPath);
  showInfo(`Status report written to .aigap/releases/status-${version}.md`);
}

async function cmdStaleness(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = getAigapDir(root);
  const policiesPath = path.join(aigapDir, "POLICIES.md");

  if (!fs.existsSync(policiesPath)) {
    showError("POLICIES.md not found. Run aigap: Initialize first.");
    return;
  }

  const content = fs.readFileSync(policiesPath, "utf-8");
  const ids = [...content.matchAll(/GP-(\d{3})/g)].map((m) => m[0]);

  const panel = vscode.window.createWebviewPanel("aigapStaleness", "aigap: Policy Staleness", vscode.ViewColumn.One, {});

  const rows = ids
    .map((id) => {
      const gitLog = cp.spawnSync("git", ["log", "--oneline", `-5`, `--all`, `-S`, id], {
        cwd: root,
        encoding: "utf-8",
      });
      const lastSeen = gitLog.stdout?.split("\n")[0] || "never referenced in git";
      return `<tr><td>${id}</td><td style="font-family:monospace;font-size:12px">${lastSeen}</td></tr>`;
    })
    .join("");

  panel.webview.html = `<!DOCTYPE html><html><body>
<h2>Policy Staleness</h2>
<table border="1" cellpadding="6" style="border-collapse:collapse">
<tr><th>ID</th><th>Last git reference</th></tr>
${rows}
</table>
</body></html>`;
}

async function cmdTestLinkage(): Promise<void> {
  const root = requireWorkspace();
  const aigapDir = ensureAigapDir(root);

  const grepResult = cp.spawnSync("grep", ["-rn", "GP-[0-9]\\{3\\}", path.join(root, "tests")], {
    encoding: "utf-8",
  });
  const references = grepResult.stdout || "(no GP-NNN references found in tests/)";

  const indexPath = path.join(aigapDir, "index.md");
  const existing = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, "utf-8") : "";

  const linkageSection = `\n## Test Linkage\n\`\`\`\n${references}\n\`\`\`\n`;
  fs.writeFileSync(indexPath, existing + linkageSection);
  openDocument(indexPath);
  showInfo("Test linkage appended to .aigap/index.md");
}

async function cmdIngestConfluence(): Promise<void> {
  const config = vscode.workspace.getConfiguration("aigap");
  const baseUrl = config.get<string>("confluenceBaseUrl");

  if (!baseUrl) {
    showError("Set aigap.confluenceBaseUrl in settings first.");
    vscode.commands.executeCommand("workbench.action.openSettings", "aigap.confluenceBaseUrl");
    return;
  }

  const pageId = await vscode.window.showInputBox({ prompt: "Confluence page ID or URL" });
  if (!pageId) return;

  showInfo(`Ingesting from Confluence: ${pageId} — then running aigap.init`);
  // In production: fetch page via Confluence REST API, write to temp file, call cmdInit()
  vscode.window.showInformationMessage(
    `aigap: Confluence ingest queued for page ${pageId}. Full API integration available in v0.2.0.`
  );
}

// ---------------------------------------------------------------------------
// Chat participant
// ---------------------------------------------------------------------------

function registerChatParticipant(context: vscode.ExtensionContext): void {
  if (!("chat" in vscode)) return;

  const handler: vscode.ChatRequestHandler = async (
    request: vscode.ChatRequest,
    _chatContext: vscode.ChatContext,
    stream: vscode.ChatResponseStream,
    _token: vscode.CancellationToken
  ) => {
    const root = getWorkspaceRoot();
    if (!root) {
      stream.markdown("No workspace folder open. Open a project first.");
      return;
    }

    const aigapDir = getAigapDir(root);
    const policiesPath = path.join(aigapDir, "POLICIES.md");
    const policiesContent = fs.existsSync(policiesPath)
      ? fs.readFileSync(policiesPath, "utf-8")
      : "(POLICIES.md not found — run aigap: Initialize first)";

    const userQuery = request.prompt.toLowerCase();

    if (userQuery.includes("gap") || userQuery.includes("unenforced")) {
      stream.markdown("Running gap scan...");
      await vscode.commands.executeCommand("aigap.gapReport");
      stream.markdown("Gap report written to `.aigap/gap-report.md`. Open it to see unenforced policies.");
    } else if (userQuery.includes("status") || userQuery.includes("compliance")) {
      const gpIds = (policiesContent.match(/GP-\d{3}/g) || []);
      const enforced = (policiesContent.match(/✅ enforced/g) || []).length;
      stream.markdown(
        `**Policy Status**\n\n- Policies defined: ${gpIds.length}\n- Enforced: ${enforced}\n- Gaps: ${gpIds.length - enforced}`
      );
    } else if (userQuery.includes("task") || userQuery.includes("sprint")) {
      stream.markdown("Generating sprint feed from gap report...");
      await vscode.commands.executeCommand("aigap.sprintFeed");
    } else {
      stream.markdown(
        `**aigap** — AI Guardrails and Policies\n\nI can help you with:\n- \`@aigap gaps\` — list unenforced policies\n- \`@aigap status\` — compliance overview\n- \`@aigap task GP-NNN\` — generate a sprint task\n\nOr ask in plain English: *"What policies are unenforced?"*`
      );
    }
  };

  const participant = (vscode as unknown as { chat: { createChatParticipant: (id: string, handler: vscode.ChatRequestHandler) => vscode.ChatParticipant } }).chat.createChatParticipant(
    "aigap.participant",
    handler
  );
  participant.iconPath = new vscode.ThemeIcon("shield");
  context.subscriptions.push(participant);
}

// ---------------------------------------------------------------------------
// Activation
// ---------------------------------------------------------------------------

export function activate(context: vscode.ExtensionContext): void {
  const commands: [string, () => Promise<void>][] = [
    ["aigap.init", cmdInit],
    ["aigap.update", cmdUpdate],
    ["aigap.validate", cmdValidate],
    ["aigap.gapReport", cmdGapReport],
    ["aigap.enforcement", cmdEnforcement],
    ["aigap.auditReport", cmdAuditReport],
    ["aigap.changeImpact", cmdChangeImpact],
    ["aigap.frameworkMap", cmdFrameworkMap],
    ["aigap.sprintFeed", cmdSprintFeed],
    ["aigap.prDraft", cmdPrDraft],
    ["aigap.releaseNotes", cmdReleaseNotes],
    ["aigap.statusReport", cmdStatusReport],
    ["aigap.staleness", cmdStaleness],
    ["aigap.testLinkage", cmdTestLinkage],
    ["aigap.ingestConfluence", cmdIngestConfluence],
  ];

  for (const [id, handler] of commands) {
    context.subscriptions.push(
      vscode.commands.registerCommand(id, async () => {
        try {
          await handler();
        } catch (err) {
          if (err instanceof Error && err.message !== "No workspace") {
            showError(err.message);
          }
        }
      })
    );
  }

  registerChatParticipant(context);
}

export function deactivate(): void {}
